### ISSUE TITLE
gitlab-ci template: fix bookdown templates

### ISSUE THREAD

**Issue by statnmap** [statnmap/gitlabr#47]
and maybe check too...

For `REPO_NAME` and/or `CRAN` to be used, `options()` must be set up over `.Rprofile.site` already modified by "r/r-verse"

```yaml
variables:
  GIT_DEPTH: 10
  REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
  CRAN: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
  R_LIBS: "ci/lib"

book-production:
    stage: book-create
    only:
        - production
    script:
        - echo "options(repos = c(CRAN = '${CRAN}'), download.file.method = 'libcurl')" >> ${R_HOME}/etc/Rprofile.site
```
